### ISSUE TITLE
trying to enter my java server

### ISSUE THREAD

**Issue by cicatrice74** [GeyserMC/GeyserAndroid#16]
![image](https://user-images.githubusercontent.com/12576766/103030385-fcc45d80-455b-11eb-960b-8075070bbab6.png)

**Comment by rtm516** [comment]
Can you provide a dump? In the app start geyser and type the command `geyser dump` then share the link here

**Comment by Chew** [comment]
No reply in almost a year, going to have to close this due to inactivity. Thank you for reporting!
