### ISSUE TITLE
Jumping problem

### ISSUE THREAD

**Issue by digra55** [GeyserMC/GeyserAndroid#18]
When jumping on a block and when swimming in water, throws it back on the block

**Comment by Chew** [comment]
This is an issue with Geyser, not GeyserAndroid. Please search for and open an issue if needed [here](https://github.com/GeyserMC/Geyser/issues/new/choose).

**Comment by digra55** [comment]
Such a problem arose with GeyserAndroid, I ran Geyser from the computer there everything is ok.

**Comment by digra55** [comment]
DEBUG - Teleport from 950.45245 66.001335 1431.7195
DEBUG - to 950.4927 65.0 1431.7
DEBUG - Confirmed teleport 9
DEBUG - Teleport from 950.4622 65.7532 1431.7
DEBUG - to 950.4927 65.0 1431.7
DEBUG - Confirmed teleport 10
DEBUG - Teleport from 950.47705 65.7532 1431.7
DEBUG - to 950.4927 65.0 1431.7
DEBUG - Confirmed teleport 11
DEBUG - Could not find packet for RequestChunkRadiusPacket
DEBUG - Could not find packet for RequestChunkRadiusPacket

**Comment by rtm516** [comment]
Its likely caused by the limitation of androids speed, but as the code that manages this is part of the core Geyser codebase so it is not a GeyserAndroid issue.
