### ISSUE TITLE
Gesyer not working

### ISSUE THREAD

**Issue by POTATOEXE** [GeyserMC/GeyserAndroid#20]
Wen te 16.220 update came out for mc geyser stopt working it sed it was on a outdated proxy (I downloaded geyser on 22 March) so I downloaded the newest build and filed the poort and the IP I started mc and i saw the loading world and resources etc but then it went back to were you join the server 
And If you try to join again it ses connecting to multiplayer and times out

Vid

I have a video of it but I dont know how to send it

**Android App Version**
My android version is android 10
My mc version is the latest (16.220
(Play store version so I cant put in a older version)

**Geyser Version**
My geyser version is 1.3.1 
My  build is113 I think

`geyser dump>https://dump.geysermc.org/VDaZHnCp9A3OfgLPVGMNPL7bEBMWbOIE

**Comment by rtm516** [comment]
Is this using the LAN proxy feature?

**Comment by POTATOEXE** [comment]
In geyser or minecraft

**Comment by Camotoy** [comment]
This should now be fixed.

**Comment by POTATOEXE** [comment]
I wil try it out now

**Comment by POTATOEXE** [comment]
It works
