### ISSUE TITLE
android app store

### ISSUE THREAD

**Issue by Minecon724** [GeyserMC/GeyserAndroid#22]
### What feature do you want to see added?

How about adding the app to F-Droid?

### Are there any alternatives?

Google play, apk mirror

**Comment by rtm516** [comment]
I looked into adding it to F-Droid but due to their requirements for the build it would not be feasible to release on there. As for Google Play we would like to but haven't got it on there yet.

**Comment by lukeeey** [comment]
It shouldn’t be long until we get it on Google Play, I need to update the draft release with the latest apk and then it shouldn’t be long

**Comment by creeper6530** [comment]
By the way, in fall, there are planned many changes to Play Store publising, so better act quickly:

https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html

If you will release your app after August, you'll need to make many changes, so better to publish it before August and have no hassle with new changes.

**Comment by Chew** [comment]
No real rush because we'd need to update it before November anyway. May as well get it over with now.

**Comment by LegacyGamerHD** [comment]
keep i mind for today you will need scoped storage or it wont be accepted

**Comment by Minecon724** [comment]
any info?

**Comment by Chew** [comment]
The app is basically abandoned at this point due to requiring Java 16, while Android only supports "8."

Gonna go ahead and close this since the likelihood of Android ever updating is very slim.

**Comment by Camotoy** [comment]
GeyserAndroid may be updated, but currently the Protocol library needs adjustments to support Android.

**Comment by lukeeey** [comment]
^ that doesn’t mean it will *never* happen, but Android support is very low priority right now so don’t keep your hopes up
